// <auto-generated />
using Labo_2.DataLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Labo_2.Migrations
{
    [DbContext(typeof(Model))]
    partial class ModelModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("DocentOpo", b =>
                {
                    b.Property<int>("DocentListId")
                        .HasColumnType("int");

                    b.Property<int>("OpoListId")
                        .HasColumnType("int");

                    b.HasKey("DocentListId", "OpoListId");

                    b.HasIndex("OpoListId");

                    b.ToTable("DocentOpo");
                });

            modelBuilder.Entity("Labo_2.Logica.Opo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Semester")
                        .HasColumnType("int");

                    b.Property<int>("Stp")
                        .HasColumnType("int");

                    b.Property<int>("fase")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Opo");
                });

            modelBuilder.Entity("Labo_2.Logica.Persoon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Familienaam")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Voornaam")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Persoon");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Persoon");
                });

            modelBuilder.Entity("OpoStudent", b =>
                {
                    b.Property<int>("OpoListId")
                        .HasColumnType("int");

                    b.Property<int>("StudentListId")
                        .HasColumnType("int");

                    b.HasKey("OpoListId", "StudentListId");

                    b.HasIndex("StudentListId");

                    b.ToTable("OpoStudent");
                });

            modelBuilder.Entity("Labo_2.Logica.Personeelslid", b =>
                {
                    b.HasBaseType("Labo_2.Logica.Persoon");

                    b.Property<string>("Personnelsnummer")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasDiscriminator().HasValue("Personeelslid");
                });

            modelBuilder.Entity("Labo_2.Logica.Student", b =>
                {
                    b.HasBaseType("Labo_2.Logica.Persoon");

                    b.Property<string>("Studentnummer")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasDiscriminator().HasValue("Student");
                });

            modelBuilder.Entity("Labo_2.Logica.Docent", b =>
                {
                    b.HasBaseType("Labo_2.Logica.Personeelslid");

                    b.HasDiscriminator().HasValue("Docent");
                });

            modelBuilder.Entity("DocentOpo", b =>
                {
                    b.HasOne("Labo_2.Logica.Docent", null)
                        .WithMany()
                        .HasForeignKey("DocentListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Labo_2.Logica.Opo", null)
                        .WithMany()
                        .HasForeignKey("OpoListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OpoStudent", b =>
                {
                    b.HasOne("Labo_2.Logica.Opo", null)
                        .WithMany()
                        .HasForeignKey("OpoListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Labo_2.Logica.Student", null)
                        .WithMany()
                        .HasForeignKey("StudentListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
